# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dima/Documents/Kernel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dima/Documents/Kernel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dima/Documents/Kernel/CMakeFiles /home/dima/Documents/Kernel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dima/Documents/Kernel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Kernel.bin

# Build rule for target.
Kernel.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Kernel.bin
.PHONY : Kernel.bin

# fast build rule for target.
Kernel.bin/fast:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/build
.PHONY : Kernel.bin/fast

kernel.o: kernel.c.o

.PHONY : kernel.o

# target to build an object file
kernel.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/kernel.c.o
.PHONY : kernel.c.o

kernel.i: kernel.c.i

.PHONY : kernel.i

# target to preprocess a source file
kernel.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/kernel.c.i
.PHONY : kernel.c.i

kernel.s: kernel.c.s

.PHONY : kernel.s

# target to generate assembly for a file
kernel.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/kernel.c.s
.PHONY : kernel.c.s

lib/ascii.o: lib/ascii.c.o

.PHONY : lib/ascii.o

# target to build an object file
lib/ascii.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/ascii.c.o
.PHONY : lib/ascii.c.o

lib/ascii.i: lib/ascii.c.i

.PHONY : lib/ascii.i

# target to preprocess a source file
lib/ascii.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/ascii.c.i
.PHONY : lib/ascii.c.i

lib/ascii.s: lib/ascii.c.s

.PHONY : lib/ascii.s

# target to generate assembly for a file
lib/ascii.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/ascii.c.s
.PHONY : lib/ascii.c.s

lib/char.o: lib/char.c.o

.PHONY : lib/char.o

# target to build an object file
lib/char.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/char.c.o
.PHONY : lib/char.c.o

lib/char.i: lib/char.c.i

.PHONY : lib/char.i

# target to preprocess a source file
lib/char.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/char.c.i
.PHONY : lib/char.c.i

lib/char.s: lib/char.c.s

.PHONY : lib/char.s

# target to generate assembly for a file
lib/char.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/char.c.s
.PHONY : lib/char.c.s

lib/draw.o: lib/draw.c.o

.PHONY : lib/draw.o

# target to build an object file
lib/draw.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/draw.c.o
.PHONY : lib/draw.c.o

lib/draw.i: lib/draw.c.i

.PHONY : lib/draw.i

# target to preprocess a source file
lib/draw.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/draw.c.i
.PHONY : lib/draw.c.i

lib/draw.s: lib/draw.c.s

.PHONY : lib/draw.s

# target to generate assembly for a file
lib/draw.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/draw.c.s
.PHONY : lib/draw.c.s

lib/input.o: lib/input.c.o

.PHONY : lib/input.o

# target to build an object file
lib/input.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/input.c.o
.PHONY : lib/input.c.o

lib/input.i: lib/input.c.i

.PHONY : lib/input.i

# target to preprocess a source file
lib/input.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/input.c.i
.PHONY : lib/input.c.i

lib/input.s: lib/input.c.s

.PHONY : lib/input.s

# target to generate assembly for a file
lib/input.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/input.c.s
.PHONY : lib/input.c.s

lib/io.o: lib/io.c.o

.PHONY : lib/io.o

# target to build an object file
lib/io.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/io.c.o
.PHONY : lib/io.c.o

lib/io.i: lib/io.c.i

.PHONY : lib/io.i

# target to preprocess a source file
lib/io.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/io.c.i
.PHONY : lib/io.c.i

lib/io.s: lib/io.c.s

.PHONY : lib/io.s

# target to generate assembly for a file
lib/io.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/io.c.s
.PHONY : lib/io.c.s

lib/memlib.o: lib/memlib.c.o

.PHONY : lib/memlib.o

# target to build an object file
lib/memlib.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/memlib.c.o
.PHONY : lib/memlib.c.o

lib/memlib.i: lib/memlib.c.i

.PHONY : lib/memlib.i

# target to preprocess a source file
lib/memlib.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/memlib.c.i
.PHONY : lib/memlib.c.i

lib/memlib.s: lib/memlib.c.s

.PHONY : lib/memlib.s

# target to generate assembly for a file
lib/memlib.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/memlib.c.s
.PHONY : lib/memlib.c.s

lib/print.o: lib/print.c.o

.PHONY : lib/print.o

# target to build an object file
lib/print.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/print.c.o
.PHONY : lib/print.c.o

lib/print.i: lib/print.c.i

.PHONY : lib/print.i

# target to preprocess a source file
lib/print.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/print.c.i
.PHONY : lib/print.c.i

lib/print.s: lib/print.c.s

.PHONY : lib/print.s

# target to generate assembly for a file
lib/print.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/print.c.s
.PHONY : lib/print.c.s

lib/sleep.o: lib/sleep.c.o

.PHONY : lib/sleep.o

# target to build an object file
lib/sleep.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/sleep.c.o
.PHONY : lib/sleep.c.o

lib/sleep.i: lib/sleep.c.i

.PHONY : lib/sleep.i

# target to preprocess a source file
lib/sleep.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/sleep.c.i
.PHONY : lib/sleep.c.i

lib/sleep.s: lib/sleep.c.s

.PHONY : lib/sleep.s

# target to generate assembly for a file
lib/sleep.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/sleep.c.s
.PHONY : lib/sleep.c.s

lib/utils.o: lib/utils.c.o

.PHONY : lib/utils.o

# target to build an object file
lib/utils.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/utils.c.o
.PHONY : lib/utils.c.o

lib/utils.i: lib/utils.c.i

.PHONY : lib/utils.i

# target to preprocess a source file
lib/utils.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/utils.c.i
.PHONY : lib/utils.c.i

lib/utils.s: lib/utils.c.s

.PHONY : lib/utils.s

# target to generate assembly for a file
lib/utils.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/utils.c.s
.PHONY : lib/utils.c.s

lib/vars.o: lib/vars.c.o

.PHONY : lib/vars.o

# target to build an object file
lib/vars.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/vars.c.o
.PHONY : lib/vars.c.o

lib/vars.i: lib/vars.c.i

.PHONY : lib/vars.i

# target to preprocess a source file
lib/vars.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/vars.c.i
.PHONY : lib/vars.c.i

lib/vars.s: lib/vars.c.s

.PHONY : lib/vars.s

# target to generate assembly for a file
lib/vars.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/vars.c.s
.PHONY : lib/vars.c.s

lib/vga.o: lib/vga.c.o

.PHONY : lib/vga.o

# target to build an object file
lib/vga.c.o:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/vga.c.o
.PHONY : lib/vga.c.o

lib/vga.i: lib/vga.c.i

.PHONY : lib/vga.i

# target to preprocess a source file
lib/vga.c.i:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/vga.c.i
.PHONY : lib/vga.c.i

lib/vga.s: lib/vga.c.s

.PHONY : lib/vga.s

# target to generate assembly for a file
lib/vga.c.s:
	$(MAKE) -f CMakeFiles/Kernel.bin.dir/build.make CMakeFiles/Kernel.bin.dir/lib/vga.c.s
.PHONY : lib/vga.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Kernel.bin"
	@echo "... kernel.o"
	@echo "... kernel.i"
	@echo "... kernel.s"
	@echo "... lib/ascii.o"
	@echo "... lib/ascii.i"
	@echo "... lib/ascii.s"
	@echo "... lib/char.o"
	@echo "... lib/char.i"
	@echo "... lib/char.s"
	@echo "... lib/draw.o"
	@echo "... lib/draw.i"
	@echo "... lib/draw.s"
	@echo "... lib/input.o"
	@echo "... lib/input.i"
	@echo "... lib/input.s"
	@echo "... lib/io.o"
	@echo "... lib/io.i"
	@echo "... lib/io.s"
	@echo "... lib/memlib.o"
	@echo "... lib/memlib.i"
	@echo "... lib/memlib.s"
	@echo "... lib/print.o"
	@echo "... lib/print.i"
	@echo "... lib/print.s"
	@echo "... lib/sleep.o"
	@echo "... lib/sleep.i"
	@echo "... lib/sleep.s"
	@echo "... lib/utils.o"
	@echo "... lib/utils.i"
	@echo "... lib/utils.s"
	@echo "... lib/vars.o"
	@echo "... lib/vars.i"
	@echo "... lib/vars.s"
	@echo "... lib/vga.o"
	@echo "... lib/vga.i"
	@echo "... lib/vga.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

